export const REQUESTS = {
  LOGIN: 'login',
  LOGOUT: 'logout',
  IS_LOGGED_IN: 'is_logged_in',
  START: 'start',
  STOP: 'stop',
  IS_RUNNING: 'is_running',
  GET_PHONE_NUMBER: 'get_phone_number',
  GET_PEERS: 'get_peers',
  SET_PEERS: 'set_peers',
  ADD_PEER: 'add_peer',
  ADD_PEERS: 'add_peers',
  REMOVE_PEER: 'remove_peer',
  REMOVE_PEERS: 'remove_peers',
  GET_PATTERNS: 'get_patterns',
  SET_PATTERNS: 'set_patterns',
  ADD_PATTERN: 'add_pattern',
  ADD_PATTERNS: 'add_patterns',
  REMOVE_PATTERN: 'remove_pattern',
  REMOVE_PATTERNS: 'remove_patterns',
  GET_EMAILS: 'get_emails',
  SET_EMAILS: 'set_emails',
  ADD_EMAIL: 'add_email',
  ADD_EMAILS: 'add_emails',
  REMOVE_EMAIL: 'remove_email',
  REMOVE_EMAILS: 'remove_emails'
};
